[package]
name = "diffeq-rs"
version = "0.1.0"
authors = ["Matthias Seitz <matthias.seitz@tum.de>"]
license = "MIT OR Apache-2.0"
readme = "README.md"
description = "Differential Equations in rust"
documentation = "https://docs.rs/diffeq/"
repository = "https://github.com/mattsse/diffeq-rs"
keywords = ["math", "algebra", "differential", "equations"]
categories = ["science"]
edition = "2018"

[dependencies]
ndarray = "0.12"
nalgebra = "0.18"
num = "0.2"
alga = "0.9"
doc-comment = "0.3"
derive_builder = "0.7"
lazy_static = "1.3"
num-traits = "0.2"
itertools = "0.8.0"
itertools-num = "0.1.3"
cast = "0.2.2"

[features]
problems = []
plot = []
